[book]
authors = ["Jan Gaura", "Jakub Beránek", "Daniel Trnka"]
language = "cs"
multilingual = false
src = "src"
title = "Úvod do programování"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/mrlvsb/upr-skripta"
default-theme = "rust"
preferred-dark-theme = "rust"
additional-js = [
  "theme/mode-c_cpp.min.js",
]
additional-css = ["theme/css/tufte.css"]
mathjax-support = true
google-analytics = "UA-177556287-1"

[output.html.playground]
editable = true

[output.html.fold]
enable = true
level = 1
